// Package goline implements the go-line-subst/v1 transform, a lossless
// line-level substitution for .go files. Frequently-repeated lines are
// replaced with 2-byte tokens (\x00 + 1-byte index) before zstd compression,
// exploiting the high line-level redundancy found in Go source corpora.
package goline

import (
	"bufio"
	"bytes"
	"context"
	"fmt"
	"io"
	"path/filepath"
	"strings"

	"github.com/arhuman/metarc-go/pkg/marc"
)

const goLineSubstID marc.TransformID = "go-line-subst/v1"

// dict contains frequent Go source lines (whitespace-stripped),
// indexed by token byte value. Immutable for go-line-subst/v1.
var dict = [...]string{
	`"bytes"`,
	`"context"`,
	`"errors"`,
	`"flag"`,
	`"github.com/stretchr/testify/assert"`,
	`"github.com/stretchr/testify/require"`,
	`"golang.org/x/sync/errgroup"`,
	`"golang.org/x/sys/unix"`,
	`"golang.org/x/sys/windows"`,
	`"log/slog"`,
	`"math/rand"`,
	`"net/http/httptest"`,
	`"net/url"`,
	`"os/exec"`,
	`"reflect"`,
	`"regexp"`,
	`"slices"`,
	`"strconv"`,
	`"strings"`,
	`"sync/atomic"`,
	`"testing"`,
	`"time"`,
	`} else {`,
	`// +optional`,
	`// Code generated by running "go generate" in`,
	`// Copyright 201`,
	`// Copyright 202`,
	`// distributed under the License is distributed on an "AS IS" BASIS,`,
	`// license that can be found in the LICENSE file.`,
	`// Licensed under the Apache License, Version 2.0 (the "License");`,
	`// limitations under the License.`,
	`// See the License for the specific language governing permissions and`,
	`// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT`,
	`// Unless required by applicable law or agreed to in writing, software`,
	`// Use of this source code is governed by a BSD-style`,
	`// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.`,
	`// you may not use this file except in compliance with the License.`,
	`// You may obtain a copy of the License at`,
	`//go:build linux`,
	`//go:noinline`,
	`assert.NoError(t, err)`,
	`cancel()`,
	`continue`,
	`default:`,
	`defer cancel()`,
	`defer f.Close()`,
	`defer func() {`,
	`defer resp.Body.Close()`,
	`defer wg.Done()`,
	`distributed under the License is distributed on an "AS IS" BASIS,`,
	`errors = append(errors, err)`,
	`f.Close()`,
	`func _() {`,
	`func init() {`,
	`func main() {`,
	`go func() {`,
	`http://www.apache.org/licenses/LICENSE-2.0`,
	`if !ok {`,
	`if err != nil {`,
	`if err == nil {`,
	`if got != want {`,
	`if n == 0 {`,
	`if ok {`,
	`if testing.Short() {`,
	`import (`,
	`Licensed under the Apache License, Version 2.0 (the "License");`,
	`limitations under the License.`,
	`log.Fatal(err)`,
	`now := time.Now()`,
	`os.Exit(1)`,
	`package main`,
	`panic(err)`,
	`return "", err`,
	`return 0, err`,
	`return 0, false`,
	`return 0`,
	`return 1`,
	`return err`,
	`return false, err`,
	`return false, nil`,
	`return false`,
	`return nil, err`,
	`return nil, false`,
	`return nil, nil`,
	`return nil`,
	`return out`,
	`return result, nil`,
	`return result`,
	`return true, nil`,
	`return true`,
	`return`,
	`runtime.GC()`,
	`See the License for the specific language governing permissions and`,
	`select {`,
	`switch {`,
	`t.Fatal(err)`,
	`t.Parallel()`,
	`Unless required by applicable law or agreed to in writing, software`,
	`var err error`,
	`wg.Add(1)`,
	`wg.Done()`,
	`wg.Wait()`,
	`WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.`,
	`you may not use this file except in compliance with the License.`,
	`You may obtain a copy of the License at`,
}

// dictLookup maps a stripped line to its encoded byte value.
// The encoded byte skips 0x00 (marker) and 0x0a (newline) to avoid
// conflicting with the line delimiter used by bufio.Reader.ReadString.
var dictLookup map[string]byte

// encodeIndex maps a dictionary index (0..104) to an encoded byte,
// skipping 0x00 and 0x0a.
func encodeIndex(i int) byte {
	b := i + 1 // skip 0x00
	if b >= 0x0a {
		b++ // skip 0x0a
	}
	return byte(b)
}

// decodeIndex maps an encoded byte back to a dictionary index.
func decodeIndex(b byte) int {
	i := int(b)
	if i > 0x0a {
		i-- // undo 0x0a skip
	}
	i-- // undo 0x00 skip
	return i
}

func init() {
	dictLookup = make(map[string]byte, len(dict))
	for i, s := range dict {
		dictLookup[s] = encodeIndex(i)
	}
}

// GoLineSubst implements the go-line-subst/v1 transform.
type GoLineSubst struct{}

// NewGoLineSubst returns a new GoLineSubst transform.
func NewGoLineSubst() *GoLineSubst { return &GoLineSubst{} }

// ID returns the stable transform identifier.
func (g *GoLineSubst) ID() marc.TransformID { return goLineSubstID }

// Applicable returns true for .go files with size > 0.
func (g *GoLineSubst) Applicable(_ context.Context, e marc.Entry, facts marc.Facts) bool {
	return filepath.Ext(e.RelPath) == ".go" && facts.Size > 0
}

// CostEstimate returns estimated gain and CPU cost.
func (g *GoLineSubst) CostEstimate(_ marc.Entry, facts marc.Facts) (gainBytes, cpuUnits int64) {
	return facts.Size / 10, facts.Size / 1024
}

// Apply reads src line-by-line, replacing dictionary-matched lines with
// 2-byte tokens (\x00 + index). The result is written as a single blob.
// Returns handled=false if the content contains NUL bytes.
func (g *GoLineSubst) Apply(ctx context.Context, _ marc.Entry, _ marc.Facts, src io.Reader, sink marc.BlobSink) (marc.Result, bool, error) {
	reader := bufio.NewReaderSize(src, 64*1024)
	var buf bytes.Buffer

	for {
		line, err := reader.ReadString('\n')
		if len(line) > 0 {
			// NUL safety: if any line contains \x00, bail out.
			if strings.ContainsRune(line, 0x00) {
				return marc.Result{}, false, nil
			}

			// Separate the trailing \n if present.
			hasNewline := strings.HasSuffix(line, "\n")
			content := line
			if hasNewline {
				content = line[:len(line)-1]
			}

			// Strip leading whitespace (tabs and spaces only).
			stripped := strings.TrimLeft(content, "\t ")
			prefix := content[:len(content)-len(stripped)]

			if idx, ok := dictLookup[stripped]; ok {
				buf.WriteString(prefix)
				buf.WriteByte(0x00)
				buf.WriteByte(idx)
			} else {
				buf.WriteString(content)
			}
			if hasNewline {
				buf.WriteByte('\n')
			}
		}
		if err == io.EOF {
			break
		}
		if err != nil {
			return marc.Result{}, false, fmt.Errorf("go-line-subst: read: %w", err)
		}
	}

	id, err := sink.Write(ctx, bytes.NewReader(buf.Bytes()))
	if err != nil {
		return marc.Result{}, false, fmt.Errorf("go-line-subst: write blob: %w", err)
	}

	return marc.Result{BlobIDs: []marc.BlobID{id}}, true, nil
}

// Reverse reconstructs the original .go file from the substituted blob.
func (g *GoLineSubst) Reverse(_ context.Context, r marc.Result, blobs marc.BlobReader, dst io.Writer) error {
	if len(r.BlobIDs) == 0 {
		return nil
	}

	rc, err := blobs.Open(r.BlobIDs[0])
	if err != nil {
		return fmt.Errorf("go-line-subst: open blob: %w", err)
	}
	defer func() { _ = rc.Close() }()

	reader := bufio.NewReaderSize(rc, 64*1024)
	w := bufio.NewWriter(dst)

	for {
		line, err := reader.ReadString('\n')
		if len(line) > 0 {
			hasNewline := strings.HasSuffix(line, "\n")
			content := line
			if hasNewline {
				content = line[:len(line)-1]
			}

			if idx := strings.IndexByte(content, 0x00); idx >= 0 {
				prefix := content[:idx]
				if idx+1 < len(content) {
					dictIdx := decodeIndex(content[idx+1])
					if dictIdx >= 0 && dictIdx < len(dict) {
						if _, err := w.WriteString(prefix); err != nil {
							return err
						}
						if _, err := w.WriteString(dict[dictIdx]); err != nil {
							return err
						}
					} else {
						if _, err := w.WriteString(content); err != nil {
							return err
						}
					}
				} else {
					if _, err := w.WriteString(content); err != nil {
						return err
					}
				}
			} else {
				if _, err := w.WriteString(content); err != nil {
					return err
				}
			}
			if hasNewline {
				if err := w.WriteByte('\n'); err != nil {
					return err
				}
			}
		}
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("go-line-subst: read blob: %w", err)
		}
	}

	return w.Flush()
}
