// Package goline implements the go-line-subst/v1 transform, a lossless
// line-level substitution for .go files. Frequently-repeated lines are
// replaced with 2-byte tokens (\x00 + 1-byte index) before zstd compression,
// exploiting the high line-level redundancy found in Go source corpora.
package goline

import (
	"path/filepath"

	"github.com/arhuman/metarc-go/internal/store/transforms/linesubst"
	"github.com/arhuman/metarc-go/pkg/marc"
)

const goLineSubstID marc.TransformID = "go-line-subst/v1"

// dict contains frequent Go source lines (whitespace-stripped),
// indexed by token byte value. Immutable for go-line-subst/v1.
var dict = [...]string{
	`"bytes"`,
	`"context"`,
	`"errors"`,
	`"flag"`,
	`"github.com/stretchr/testify/assert"`,
	`"github.com/stretchr/testify/require"`,
	`"golang.org/x/sync/errgroup"`,
	`"golang.org/x/sys/unix"`,
	`"golang.org/x/sys/windows"`,
	`"log/slog"`,
	`"math/rand"`,
	`"net/http/httptest"`,
	`"net/url"`,
	`"os/exec"`,
	`"reflect"`,
	`"regexp"`,
	`"slices"`,
	`"strconv"`,
	`"strings"`,
	`"sync/atomic"`,
	`"testing"`,
	`"time"`,
	`} else {`,
	`// +optional`,
	`// Code generated by running "go generate" in`,
	`// Copyright 201`,
	`// Copyright 202`,
	`// distributed under the License is distributed on an "AS IS" BASIS,`,
	`// license that can be found in the LICENSE file.`,
	`// Licensed under the Apache License, Version 2.0 (the "License");`,
	`// limitations under the License.`,
	`// See the License for the specific language governing permissions and`,
	`// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT`,
	`// Unless required by applicable law or agreed to in writing, software`,
	`// Use of this source code is governed by a BSD-style`,
	`// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.`,
	`// you may not use this file except in compliance with the License.`,
	`// You may obtain a copy of the License at`,
	`//go:build linux`,
	`//go:noinline`,
	`assert.NoError(t, err)`,
	`cancel()`,
	`continue`,
	`default:`,
	`defer cancel()`,
	`defer f.Close()`,
	`defer func() {`,
	`defer resp.Body.Close()`,
	`defer wg.Done()`,
	`distributed under the License is distributed on an "AS IS" BASIS,`,
	`errors = append(errors, err)`,
	`f.Close()`,
	`func _() {`,
	`func init() {`,
	`func main() {`,
	`go func() {`,
	`http://www.apache.org/licenses/LICENSE-2.0`,
	`if !ok {`,
	`if err != nil {`,
	`if err == nil {`,
	`if got != want {`,
	`if n == 0 {`,
	`if ok {`,
	`if testing.Short() {`,
	`import (`,
	`Licensed under the Apache License, Version 2.0 (the "License");`,
	`limitations under the License.`,
	`log.Fatal(err)`,
	`now := time.Now()`,
	`os.Exit(1)`,
	`package main`,
	`panic(err)`,
	`return "", err`,
	`return 0, err`,
	`return 0, false`,
	`return 0`,
	`return 1`,
	`return err`,
	`return false, err`,
	`return false, nil`,
	`return false`,
	`return nil, err`,
	`return nil, false`,
	`return nil, nil`,
	`return nil`,
	`return out`,
	`return result, nil`,
	`return result`,
	`return true, nil`,
	`return true`,
	`return`,
	`runtime.GC()`,
	`See the License for the specific language governing permissions and`,
	`select {`,
	`switch {`,
	`t.Fatal(err)`,
	`t.Parallel()`,
	`Unless required by applicable law or agreed to in writing, software`,
	`var err error`,
	`wg.Add(1)`,
	`wg.Done()`,
	`wg.Wait()`,
	`WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.`,
	`you may not use this file except in compliance with the License.`,
	`You may obtain a copy of the License at`,
}

// dictLookup mirrors the lookup map built by linesubst.New, exposed at
// package level so the package's own tests can verify dictionary integrity.
var dictLookup = buildDictLookup()

func buildDictLookup() map[string]byte {
	m := make(map[string]byte, len(dict))
	for i, s := range dict {
		m[s] = linesubst.EncodeIndex(i)
	}
	return m
}

func encodeIndex(i int) byte { return linesubst.EncodeIndex(i) }
func decodeIndex(b byte) int { return linesubst.DecodeIndex(b) }

// GoLineSubst implements the go-line-subst/v1 transform.
type GoLineSubst struct {
	*linesubst.LineSubst
}

// NewGoLineSubst returns a new GoLineSubst transform.
func NewGoLineSubst() *GoLineSubst {
	return &GoLineSubst{
		LineSubst: linesubst.New(goLineSubstID, dict[:], applicable),
	}
}

func applicable(e marc.Entry, facts marc.Facts) bool {
	return filepath.Ext(e.RelPath) == ".go" && facts.Size > 0
}
